services:
  - type: web
    name: bookit-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://bookit-server-f7n4.onrender.com/api