services:
  - type: web
    name: bookit-server
    runtime: node
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production